name: build go starter

env:
  IMAGE_NAME: go-starter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest
#          golangci-lint run ./...
      - name: Build
        run: |
          go build -v ./...


  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build . --file deploy/Dockerfile --tag $IMAGE_NAME
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u "${{ secrets.ACCESS_USERNAME }}" --password-stdin
      - name: Push Image
        run: |
          IMAGE_ID="${{ secrets.ACCESS_USERNAME }}"/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
